import { css } from 'styled-system/css';
import './globals.css';
import Header from './_components/Header';
import { bizUDPGothic } from './fonts';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={bizUDPGothic.className}>
      <body className={css({ bg: 'primary.bg' })}>
        <Header />
        <div
          className={css({
            display: 'grid',
            gridTemplateColumns:
              'repeat(4,minmax(0,1fr)) repeat(4,8rem) repeat(4,minmax(0,1fr))',
            gridColumnGap: 'gridGap.main',
            marginTop: 'header',
          })}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
